# Generated by Django 6.0.7 on 2026-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='from_email',
            field=models.CharField(choices=[('global@signaturetalks.org', 'Signature Talks (global@signaturetalks.org)'), ('contact@wynxtalks.com', 'WYNx Talks (contact@wynxtalks.com)')], default='global@signaturetalks.org', max_length=100),
        ),
    ]
