# Generated by Django 6.0.7 on 2026-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.CharField(choices=[('Signature Talks <global@signaturetalks.org>', 'Signature Talks (global@signaturetalks.org)'), ('WYNxTALKS <contact@wynxtalks.com>', 'WYNx Talks (contact@wynxtalks.com)')], default='Signature Talks <global@signaturetalks.org>', max_length=100),
        ),
    ]
