# Generated by Django 6.0.7 on 2026-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.CharField(choices=[('Signature Talks <global@signaturetalks.org>', 'Signature Talks (global@signaturetalks.org)'), ('WYNxTALKS <contact@wynxtalks.com>', 'WYNx Talks (contact@wynxtalks.com)'), ('VOICETALKS <info@voicetalks.org>', 'Voice Talks (info@voicetalks.org)')], default='Signature Talks <global@signaturetalks.org>', max_length=100),
        ),
    ]
