# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.CharField(default='Signature Talks <global@signaturetalks.org>', max_length=100),
        ),
    ]
