# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_campaign_from_email'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contactlist')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='advance_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.advancecampaign'),
        ),
    ]
