# Generated by Django 6.0.7 on 2026-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_advancecampaign_campaign_advance_campaign'),
        ('contacts', '0004_contactbatch_contact_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_batches',
            field=models.ManyToManyField(blank=True, help_text='If selected, only send to these batches. Otherwise send to entire list.', to='contacts.contactbatch'),
        ),
    ]
