# Generated by Django 6.0.7 on 2026-09-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_advancecampaign_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True, max_length=255)),
                ('scheduling_link', models.URLField(blank=True, max_length=255)),
                ('physical_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='podcast_sender',
            field=models.ForeignKey(blank=True, help_text='Sender details injected into Universal Podcast Template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.podcastsender'),
        ),
    ]
