# Generated by Django 6.0.7 on 2026-09-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_podcastsender_campaign_podcast_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_string', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.podcastsender')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event details to inject into templates', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.event'),
        ),
    ]
