# Generated by Django 6.0.7 on 2026-09-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_event_campaign_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
