# Generated by Django 6.0.7 on 2026-07-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.IntegerField(default=0)),
                ('total_opens', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_bounces', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='campaigns.campaign')),
            ],
        ),
    ]
