# Generated by Django 6.0.7 on 2026-08-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_campaignperformance_total_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignperformance',
            name='total_blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='total_complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='total_deferred',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='total_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='total_hard_bounces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='total_invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='total_soft_bounces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='total_unsubscribed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignrecipientstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to provider'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('deferred', 'Deferred'), ('unsubscribed', 'Unsubscribed'), ('complaint', 'Complaint (Spam)'), ('hard_bounce', 'Hard Bounce'), ('soft_bounce', 'Soft Bounce'), ('invalid_email', 'Invalid Email'), ('blocked', 'Blocked'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
