# Generated by Django 6.0.7 on 2026-08-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_campaignperformance_total_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipientstatus',
            name='clicked_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaignrecipientstatus',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
