# Generated by Django 6.0.7 on 2026-09-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_merge_masterlinksettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipientstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to provider'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bot_scanned', 'Bot Scanned'), ('failed', 'Failed'), ('deferred', 'Deferred'), ('unsubscribed', 'Unsubscribed'), ('complaint', 'Complaint (Spam)'), ('hard_bounce', 'Hard Bounce'), ('soft_bounce', 'Soft Bounce'), ('invalid_email', 'Invalid Email'), ('blocked', 'Blocked'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
