# Generated by Django 6.0.7 on 2026-07-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
