# Generated by Django 6.0.7 on 2026-09-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactlist_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='contacts.contactlist')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contactbatch'),
        ),
    ]
