# Generated by Django 6.0.7 on 2026-09-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='contacts_co_first_n_57a3e4_idx',
            old_name='contacts_co_first_n_08bb97_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='contacts_co_created_c1a2bf_idx',
            old_name='contacts_co_created_466471_idx',
        ),
    ]
