# Generated by Django 6.0.7 on 2026-07-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
