# Generated by Django 6.0.7 on 2026-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
